package com.tiem625.lines.event

enum class GameEventTypes {

    RECEIVE_POINTS,
    UPDATE_GRID,
    GROUP_REMOVE_BALL,
    CHANGE_MULTIPLIER,
    MENU_OPTION_SELECTED,
    OPTIONS_OPTION_SELECTED,
    GAME_OVER,
    STAGE_ESCAPE,
    DIALOG_APPEAR,
    DIALOG_DISMISS,
    LEADERBOARD_ENTRY,
    USED_MUSIC_CONTROLS,
    SKIP_INTRO,
    SCORE_PROGRESS_FULL,
    MULTIPLIER_BONUS_OVER
}